# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
#    param_fetcher_listener:  true
    allowed_methods_listener:  true
#    routing_loader: true
    view:
        view_response_listener:  true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors # This is the default value
    exception:
        codes:
            'Doctrine\ORM\EntityNotFoundException': 404
        messages:
            'Doctrine\ORM\EntityNotFoundException': true
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
